name: connect-deploy

on:
  pull_request:
  merge_group:

jobs:
  connect-deploy:
    uses: BristolMyersSquibb/blockr.ci/.github/workflows/connect-deploy.yaml@main
    permissions:
      contents: read
    with:
      auth: deploy-key
      r-version: "4.4.2"
    secrets:
      DEPLOY_KEY: ${{ secrets.CONNECT_DEPLOY_SSH_KEY }}
